<?php

/**
 * @file
 * Contains todo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function todo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the todo module.
    case 'help.page.todo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Todo Module') . '</p>';
      return $output;

    default:
  }
}

function todo_theme()
{
    $theme['todo_list'] = [
        'variables' => ['todos' => []],
    ];
    $theme['todo_details'] = [
        'variables' => ['todo' => null]
    ];
    return $theme;
}
